{{- $name := include "name" . -}}
{{- $chart := include "chart" . -}}

{{- range  $.Values.serviceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ . }}
  namespace: {{ $.Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ . }}@{{ $.Values.projectId}}.iam.gserviceaccount.com"
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/version: {{ $.Values.version | quote }}
    helm.sh/chart: {{ $chart }}
---
{{- end }}
